# Generated by Django 6.0 on 2026-01-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_collector_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='profile_photo',
            field=models.ImageField(upload_to='collectors/profile/'),
        ),
    ]
